### ISSUE TITLE
Using static GPS values without GPS waveforms

### ISSUE THREAD

**Issue by degoldberg** [slipinversion/WASP#4]
(I can't remember if this is already in place)

Ability to use static displacements (a single set of NEU values) in the inversion, separate from cGPS waveforms

**Comment by pakk583** [comment]
This is indeed in place. 

However, currently one must add waveforms to the GPS data to be able to perform inversions with this code. Not necesarily cGPS waveforms, but there must be waveforms added, for this code currently can't invert only GPS data.
