### ISSUE TITLE
Small magnitude modifications for automatic solution

### ISSUE THREAD

**Issue by degoldberg** [slipinversion/WASP#6]
Include set of rules to ensure that there are a useful number of subfaults in the initial automatic solution.
Perhaps M6s get 3x3 subfaults, M7s get 6x6 subfaults, >M8s get 10x10 subfaults or some more specific magnitude scaling sizes

**Comment by pakk583** [comment]
Previously the minimum subfault size was set to 10x10 km^2. Now, this minimum subfault size was changed to 1x1 km^2. For instance, with this new setting, for the Mw 7.1 Ridgecrest earthquake, one gets subfault sizes of 4x3.3 km^2 for the automatic solution.
